parameters:
- name: env
  displayName: Environment Name
  type: string
  default: dev
  values:
  - dev
  - test

trigger: none

variables:
- group: "mdw-shared-westeurope-01"

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '1.0.3'
- task: CmdLine@2
  displayName: Terraform Init
  inputs:
    script: 'env TF_WORKSPACE=default terraform init -input=false -backend-config="access_key=$(storage-key1)"'
    workingDirectory: '$(Build.Repository.LocalPath)/iac'
- task: CmdLine@2
  displayName: Terraform Select Workspace
  # Create workspace if not exist https://github.com/hashicorp/terraform/issues/21393
  inputs:
    script: 'terraform workspace select ${{ parameters.env }} || terraform workspace new ${{ parameters.env }}'
    workingDirectory: '$(Build.Repository.LocalPath)/iac'
- task: CmdLine@2
  displayName: Terraform Validate
  inputs:
    script: 'terraform validate'
    workingDirectory: '$(Build.Repository.LocalPath)/iac'
- task: CmdLine@2
  displayName: Terraform Plan
  inputs:
    script: 'terraform plan -input=false -var="env=${{ parameters.env }}" -var="subscription_id=$(tf-ado-syn-subscription-id)" -var="spn-client-id=$(tf-ado-syn-spn-client-id)" -var="spn-client-secret=$(tf-ado-syn-spn-client-secret)" -var="spn-tenant-id=$(tf-ado-syn-spn-tenant-id)" -var="tf-ado-syn-admins=$(tf-ado-syn-admins)"'
    workingDirectory: '$(Build.Repository.LocalPath)/iac'
